import type { Metadata } from "next";
import Insaniburger from 'next/font/local';
import "./globals.css";

const insaniburger = Insaniburger({
  src: '../fonts/Insaniburger.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={insaniburger.className}
      >
        {children}
      </body>
    </html>
  );
}
